### ISSUE TITLE
GPU required for training?

### ISSUE THREAD

**Issue by flaime-ai** [alievk/npbg#3]

**Comment by seva100** [comment]
We used GeForce GTX 1080 Ti with less than 12 GB GPU memory, which should be more than enough for training in most cases. Not sure where your issue comes from; perhaps you can try decreasing batch size if it's more than 1 in your experiment (`--batch_size` parameter of train.py). Does it happen during running the example from the readme?

**Comment by flaime-ai** [comment]
Thanks - Okay, there must be something else up.
I can get both the examples running with no problems.
I'll try decreasing the batch size.
Also, it may be to do with the point cloud generated from agisoft, I didn't optimise that.
