### ISSUE TITLE
Multi-GPU support for training?

### ISSUE THREAD

**Issue by Yurri-hub** [alievk/npbg#36]
I try to train a large-scale scene with large number of point clouds.
But I received a CUDA out of memory error at the start of training.

Is there any way to train the model on Multi-GPUs?

**Comment by seva100** [comment]
Hi @Yurri-hub, yes, you can specify `multigpu: True` in train config or `--multigpu` in command line when running `python train.py`. The indices of the GPUs used can be specified via `CUDA_VISIBLE_DEVICES="0,1,5" python train.py ...`, where indices should be specified instead of "0,1,5". Also make sure to set the `batch_size` accordingly in order to avoid memory issues.

**Comment by Yurri-hub** [comment]
Thank you for your reply. It helps a lot.
